"""empty message

Revision ID: 1936aaa9ad6e
Revises: 290122aa2398
Create Date: 2021-09-26 11:30:35.093745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1936aaa9ad6e'
down_revision = '290122aa2398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('user_surname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_surname_key', 'user', ['surname'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
